import type { WeatherData } from "./weatherData";
import type { Country } from "./countryStore";

// Helper to generate weather based on latitude band
function w(city: string, temp: number, feelsLike: number, condition: "sunny" | "cloudy" | "rainy" | "snowy" | "windy", windSpeed: number, humidity: number, rainProbability: number, afternoonRain: boolean, description: string): WeatherData {
  return { temperature: temp, feelsLike, condition, windSpeed, humidity, rainProbability, afternoonRain, city, description };
}

export const cityWeather: Record<string, WeatherData> = {
  // Etelä-Suomi (Southern Finland)
  Helsinki: w("Helsinki", -3, -8, "snowy", 12, 85, 65, true, "Lumisadetta, heikko tuuli"),
  Espoo: w("Espoo", -2, -7, "cloudy", 10, 80, 45, true, "Pilvistä, ajoittain lumikuuroja"),
  Vantaa: w("Vantaa", -3, -8, "snowy", 11, 84, 60, true, "Lumisadetta"),
  Kauniainen: w("Kauniainen", -2, -7, "cloudy", 9, 80, 45, false, "Pilvistä"),
  Kirkkonummi: w("Kirkkonummi", -2, -7, "cloudy", 11, 81, 50, true, "Pilvistä, kosteaa"),
  Siuntio: w("Siuntio", -2, -6, "cloudy", 10, 80, 45, false, "Puolipilvistä"),
  Vihti: w("Vihti", -3, -8, "snowy", 8, 82, 50, true, "Lumikuuroja"),
  Lohja: w("Lohja", -2, -7, "cloudy", 9, 81, 45, true, "Pilvistä, kosteaa"),
  Karkkila: w("Karkkila", -4, -9, "snowy", 7, 82, 50, false, "Heikkoa lumisadetta"),
  Nurmijärvi: w("Nurmijärvi", -3, -8, "cloudy", 9, 82, 45, false, "Puolipilvistä"),
  Hyvinkää: w("Hyvinkää", -4, -9, "snowy", 8, 83, 55, true, "Lumisadetta"),
  Tuusula: w("Tuusula", -3, -8, "cloudy", 9, 82, 45, false, "Pilvistä"),
  Kerava: w("Kerava", -3, -8, "cloudy", 10, 83, 50, true, "Pilvistä"),
  Järvenpää: w("Järvenpää", -3, -8, "cloudy", 9, 82, 45, false, "Puolipilvistä"),
  Mäntsälä: w("Mäntsälä", -4, -9, "snowy", 7, 83, 50, true, "Lumikuuroja"),
  Pornainen: w("Pornainen", -4, -9, "cloudy", 8, 82, 45, false, "Pilvistä"),
  Sipoo: w("Sipoo", -3, -8, "cloudy", 11, 83, 50, true, "Merituulta, pilvistä"),
  Porvoo: w("Porvoo", -3, -8, "cloudy", 10, 82, 50, true, "Pilvistä"),
  Askola: w("Askola", -4, -9, "cloudy", 8, 82, 45, false, "Puolipilvistä"),
  Pukkila: w("Pukkila", -4, -9, "cloudy", 7, 82, 45, false, "Pilvistä"),
  Myrskylä: w("Myrskylä", -4, -9, "cloudy", 7, 82, 45, false, "Puolipilvistä"),
  Loviisa: w("Loviisa", -3, -8, "cloudy", 12, 83, 55, true, "Merituulta"),
  Lapinjärvi: w("Lapinjärvi", -4, -9, "cloudy", 8, 82, 45, false, "Pilvistä"),
  Hanko: w("Hanko", -1, -6, "windy", 15, 85, 55, true, "Tuulista, mereltä kosteaa"),
  Raasepori: w("Raasepori", -2, -7, "cloudy", 11, 82, 50, true, "Pilvistä"),
  Inkoo: w("Inkoo", -2, -7, "cloudy", 12, 82, 50, true, "Merituulta"),

  // Varsinais-Suomi & Satakunta
  Turku: w("Turku", 1, -3, "rainy", 8, 88, 80, true, "Tihkusadetta, kosteaa"),
  Kaarina: w("Kaarina", 1, -3, "rainy", 8, 87, 75, true, "Tihkusadetta"),
  Raisio: w("Raisio", 1, -3, "rainy", 9, 87, 75, true, "Tihkusadetta"),
  Naantali: w("Naantali", 1, -3, "rainy", 10, 86, 70, true, "Sadetta, merituulta"),
  Masku: w("Masku", 0, -4, "cloudy", 9, 85, 60, false, "Pilvistä"),
  Mynämäki: w("Mynämäki", 0, -4, "cloudy", 8, 84, 55, false, "Puolipilvistä"),
  Nousiainen: w("Nousiainen", 0, -4, "cloudy", 8, 84, 55, false, "Pilvistä"),
  Rusko: w("Rusko", 0, -4, "cloudy", 8, 84, 55, false, "Pilvistä"),
  Lieto: w("Lieto", 0, -4, "cloudy", 8, 85, 60, false, "Pilvistä"),
  Aura: w("Aura", 0, -4, "cloudy", 7, 84, 50, false, "Puolipilvistä"),
  Pöytyä: w("Pöytyä", -1, -5, "cloudy", 7, 83, 45, false, "Puolipilvistä"),
  Loimaa: w("Loimaa", -1, -5, "cloudy", 7, 83, 45, false, "Pilvistä"),
  Oripää: w("Oripää", -1, -5, "cloudy", 7, 83, 45, false, "Puolipilvistä"),
  Marttila: w("Marttila", -1, -5, "cloudy", 7, 83, 45, false, "Pilvistä"),
  Koski_Tl: w("Koski Tl", -1, -5, "cloudy", 7, 83, 45, false, "Puolipilvistä"),
  Somero: w("Somero", -2, -7, "cloudy", 7, 82, 45, false, "Pilvistä"),
  Salo: w("Salo", 0, -4, "rainy", 10, 89, 70, true, "Räntäsadetta"),
  Paimio: w("Paimio", 0, -4, "cloudy", 9, 85, 60, false, "Pilvistä"),
  Sauvo: w("Sauvo", 0, -4, "cloudy", 9, 85, 55, false, "Puolipilvistä"),
  Parainen: w("Parainen", 1, -3, "rainy", 11, 87, 70, true, "Merituulta, sadetta"),
  Kemiönsaari: w("Kemiönsaari", 1, -3, "windy", 14, 86, 65, true, "Tuulista saaristossa"),
  Taivassalo: w("Taivassalo", 0, -4, "cloudy", 10, 85, 55, false, "Merituulta"),
  Kustavi: w("Kustavi", 1, -3, "windy", 13, 86, 60, true, "Tuulista saaristossa"),
  Uusikaupunki: w("Uusikaupunki", 0, -4, "cloudy", 11, 85, 55, true, "Merituulta"),
  Laitila: w("Laitila", 0, -4, "cloudy", 9, 84, 50, false, "Pilvistä"),
  Vehmaa: w("Vehmaa", 0, -4, "cloudy", 10, 84, 50, false, "Puolipilvistä"),
  Pori: w("Pori", 2, -2, "rainy", 15, 92, 85, true, "Vesisadetta, tuulista"),
  Ulvila: w("Ulvila", 1, -3, "rainy", 12, 90, 75, true, "Sadetta"),
  Nakkila: w("Nakkila", 1, -3, "rainy", 11, 89, 70, true, "Sadetta"),
  Harjavalta: w("Harjavalta", 0, -4, "cloudy", 10, 87, 60, false, "Pilvistä"),
  Kokemäki: w("Kokemäki", -1, -5, "cloudy", 9, 85, 55, false, "Pilvistä"),
  Huittinen: w("Huittinen", -1, -5, "cloudy", 8, 84, 50, false, "Puolipilvistä"),
  Säkylä: w("Säkylä", -1, -5, "cloudy", 8, 84, 50, false, "Pilvistä"),
  Eura: w("Eura", 0, -4, "cloudy", 9, 85, 55, false, "Pilvistä"),
  Eurajoki: w("Eurajoki", 1, -3, "windy", 14, 88, 65, true, "Merituulta"),
  Rauma: w("Rauma", 1, -3, "rainy", 14, 90, 75, true, "Vesisadetta"),
  Kankaanpää: w("Kankaanpää", -2, -7, "cloudy", 9, 83, 45, false, "Pilvistä"),
  Karvia: w("Karvia", -3, -8, "cloudy", 8, 82, 40, false, "Puolipilvistä"),
  Jämijärvi: w("Jämijärvi", -2, -7, "cloudy", 8, 83, 45, false, "Pilvistä"),
  Siikainen: w("Siikainen", -1, -5, "cloudy", 10, 84, 50, false, "Pilvistä"),
  Pomarkku: w("Pomarkku", -1, -5, "cloudy", 10, 85, 55, false, "Puolipilvistä"),
  Merikarvia: w("Merikarvia", 0, -4, "windy", 16, 87, 60, true, "Merituulta, tuulista"),

  // Kanta-Häme
  Hämeenlinna: w("Hämeenlinna", -4, -9, "cloudy", 9, 81, 40, false, "Pilvistä"),
  Hattula: w("Hattula", -4, -9, "cloudy", 8, 81, 40, false, "Puolipilvistä"),
  Janakkala: w("Janakkala", -4, -9, "cloudy", 8, 81, 40, false, "Pilvistä"),
  Riihimäki: w("Riihimäki", -4, -9, "cloudy", 8, 80, 40, false, "Puolipilvistä"),
  Loppi: w("Loppi", -4, -9, "cloudy", 7, 81, 40, false, "Pilvistä"),
  Hausjärvi: w("Hausjärvi", -4, -9, "cloudy", 8, 81, 40, false, "Puolipilvistä"),
  Forssa: w("Forssa", -3, -8, "cloudy", 8, 81, 40, false, "Puolipilvistä"),
  Tammela: w("Tammela", -3, -8, "cloudy", 7, 81, 40, false, "Pilvistä"),
  Jokioinen: w("Jokioinen", -3, -8, "cloudy", 7, 81, 40, false, "Puolipilvistä"),
  Ypäjä: w("Ypäjä", -3, -8, "cloudy", 7, 81, 40, false, "Pilvistä"),
  Humppila: w("Humppila", -3, -8, "cloudy", 7, 81, 40, false, "Puolipilvistä"),

  // Päijät-Häme
  Lahti: w("Lahti", -4, -9, "cloudy", 7, 79, 35, false, "Puolipilvistä"),
  Hollola: w("Hollola", -4, -9, "cloudy", 7, 79, 35, false, "Puolipilvistä"),
  Asikkala: w("Asikkala", -5, -10, "cloudy", 6, 80, 35, false, "Pilvistä"),
  Padasjoki: w("Padasjoki", -5, -10, "snowy", 6, 81, 40, false, "Heikkoa lumisadetta"),
  Sysmä: w("Sysmä", -6, -11, "snowy", 6, 81, 40, false, "Lumikuuroja"),
  Hartola: w("Hartola", -6, -11, "snowy", 5, 81, 40, false, "Heikkoa lumisadetta"),
  Heinola: w("Heinola", -5, -10, "snowy", 6, 83, 45, true, "Heikkoa lumisadetta"),
  Kärkölä: w("Kärkölä", -4, -9, "cloudy", 7, 80, 35, false, "Puolipilvistä"),
  Orimattila: w("Orimattila", -4, -9, "cloudy", 7, 80, 40, false, "Pilvistä"),
  Iitti: w("Iitti", -4, -9, "cloudy", 7, 80, 40, false, "Puolipilvistä"),

  // Kymenlaakso & Etelä-Karjala
  Kouvola: w("Kouvola", -5, -10, "snowy", 7, 82, 45, true, "Heikkoa lumisadetta"),
  Kotka: w("Kotka", -2, -7, "cloudy", 13, 83, 50, true, "Pilvistä, merituulta"),
  Hamina: w("Hamina", -3, -8, "cloudy", 12, 83, 50, true, "Merituulta"),
  Pyhtää: w("Pyhtää", -3, -8, "cloudy", 12, 83, 50, false, "Pilvistä"),
  Virolahti: w("Virolahti", -3, -8, "cloudy", 13, 83, 50, true, "Merituulta"),
  Miehikkälä: w("Miehikkälä", -5, -10, "cloudy", 8, 82, 40, false, "Pilvistä"),
  Lappeenranta: w("Lappeenranta", -7, -13, "snowy", 8, 80, 35, false, "Pakkasta, lumikuuroja"),
  Imatra: w("Imatra", -8, -14, "snowy", 7, 81, 30, false, "Pakkasta"),
  Lemi: w("Lemi", -7, -13, "snowy", 6, 80, 30, false, "Pakkasta"),
  Luumäki: w("Luumäki", -7, -13, "cloudy", 7, 80, 35, false, "Pilvistä"),
  Savitaipale: w("Savitaipale", -7, -13, "snowy", 6, 81, 35, false, "Lumikuuroja"),
  Taipalsaari: w("Taipalsaari", -7, -13, "snowy", 7, 80, 30, false, "Pakkasta"),
  Rautjärvi: w("Rautjärvi", -8, -14, "snowy", 6, 80, 30, false, "Pakkasta"),
  Ruokolahti: w("Ruokolahti", -8, -14, "snowy", 6, 80, 30, false, "Pakkasta"),
  Parikkala: w("Parikkala", -9, -15, "snowy", 5, 80, 25, false, "Pakkasta"),

  // Pirkanmaa
  Tampere: w("Tampere", -5, -11, "snowy", 14, 90, 70, true, "Runsasta lumisadetta"),
  Nokia: w("Nokia", -5, -11, "snowy", 12, 88, 60, true, "Lumisadetta"),
  Ylöjärvi: w("Ylöjärvi", -5, -11, "snowy", 13, 87, 65, true, "Runsasta lumisadetta"),
  Kangasala: w("Kangasala", -5, -10, "cloudy", 10, 85, 50, false, "Pilvistä"),
  Lempäälä: w("Lempäälä", -5, -10, "snowy", 11, 86, 55, true, "Lumikuuroja"),
  Pirkkala: w("Pirkkala", -5, -10, "snowy", 12, 87, 55, true, "Lumisadetta"),
  Vesilahti: w("Vesilahti", -5, -10, "snowy", 10, 86, 50, false, "Heikkoa lumisadetta"),
  Akaa: w("Akaa", -4, -9, "cloudy", 9, 84, 45, false, "Pilvistä"),
  Valkeakoski: w("Valkeakoski", -4, -9, "cloudy", 9, 84, 45, false, "Puolipilvistä"),
  Urjala: w("Urjala", -4, -9, "cloudy", 8, 83, 40, false, "Pilvistä"),
  Sastamala: w("Sastamala", -4, -9, "cloudy", 9, 84, 50, false, "Puolipilvistä"),
  Hämeenkyrö: w("Hämeenkyrö", -5, -10, "cloudy", 10, 85, 50, false, "Pilvistä"),
  Ikaalinen: w("Ikaalinen", -5, -10, "cloudy", 9, 84, 45, false, "Puolipilvistä"),
  Parkano: w("Parkano", -5, -11, "snowy", 9, 83, 45, false, "Lumikuuroja"),
  Kihniö: w("Kihniö", -5, -11, "cloudy", 9, 83, 40, false, "Pilvistä"),
  Virrat: w("Virrat", -6, -12, "snowy", 9, 83, 45, false, "Heikkoa lumisadetta"),
  Mänttä_Vilppula: w("Mänttä-Vilppula", -6, -12, "snowy", 8, 83, 45, false, "Lumikuuroja"),
  Juupajoki: w("Juupajoki", -5, -10, "cloudy", 8, 84, 45, false, "Pilvistä"),
  Orivesi: w("Orivesi", -5, -10, "cloudy", 9, 84, 45, false, "Puolipilvistä"),
  Ruovesi: w("Ruovesi", -6, -12, "snowy", 8, 84, 45, false, "Lumikuuroja"),
  Pälkäne: w("Pälkäne", -5, -10, "cloudy", 8, 83, 40, false, "Puolipilvistä"),
  Punkalaidun: w("Punkalaidun", -3, -8, "cloudy", 8, 83, 40, false, "Pilvistä"),

  // Keski-Suomi
  Jyväskylä: w("Jyväskylä", -6, -12, "cloudy", 11, 82, 40, false, "Pilvistä, heikkoa lumisadetta"),
  Muurame: w("Muurame", -6, -12, "cloudy", 10, 82, 40, false, "Pilvistä"),
  Laukaa: w("Laukaa", -7, -13, "snowy", 9, 82, 40, false, "Lumikuuroja"),
  Jämsä: w("Jämsä", -6, -12, "snowy", 8, 82, 40, false, "Heikkoa lumisadetta"),
  Keuruu: w("Keuruu", -6, -12, "snowy", 9, 83, 45, false, "Lumikuuroja"),
  Petäjävesi: w("Petäjävesi", -7, -13, "snowy", 8, 82, 40, false, "Lumisadetta"),
  Äänekoski: w("Äänekoski", -7, -13, "snowy", 9, 82, 40, false, "Lumikuuroja"),
  Saarijärvi: w("Saarijärvi", -7, -13, "snowy", 8, 82, 40, false, "Heikkoa lumisadetta"),
  Viitasaari: w("Viitasaari", -8, -14, "snowy", 8, 81, 35, false, "Pakkasta, lumikuuroja"),
  Pihtipudas: w("Pihtipudas", -9, -15, "snowy", 8, 80, 30, false, "Pakkasta"),
  Kivijärvi: w("Kivijärvi", -8, -14, "snowy", 8, 81, 35, false, "Lumikuuroja"),
  Kannonkoski: w("Kannonkoski", -8, -14, "snowy", 7, 81, 35, false, "Pakkasta"),
  Karstula: w("Karstula", -8, -14, "snowy", 8, 81, 35, false, "Lumikuuroja"),
  Kyyjärvi: w("Kyyjärvi", -8, -14, "snowy", 8, 81, 35, false, "Pakkasta"),
  Konnevesi: w("Konnevesi", -7, -13, "snowy", 7, 82, 35, false, "Heikkoa lumisadetta"),
  Hankasalmi: w("Hankasalmi", -7, -13, "snowy", 7, 82, 35, false, "Lumikuuroja"),
  Toivakka: w("Toivakka", -7, -13, "cloudy", 8, 82, 35, false, "Pilvistä"),
  Uurainen: w("Uurainen", -7, -13, "snowy", 8, 82, 35, false, "Lumikuuroja"),
  Multia: w("Multia", -7, -13, "snowy", 8, 82, 40, false, "Heikkoa lumisadetta"),
  Kinnula: w("Kinnula", -9, -15, "snowy", 8, 80, 30, false, "Pakkasta"),
  Luhanka: w("Luhanka", -6, -12, "cloudy", 7, 82, 35, false, "Pilvistä"),

  // Etelä-Savo
  Mikkeli: w("Mikkeli", -7, -13, "snowy", 6, 83, 40, false, "Lumikuuroja"),
  Savonlinna: w("Savonlinna", -9, -15, "snowy", 5, 82, 30, false, "Pakkasta, selkeää"),
  Pieksämäki: w("Pieksämäki", -8, -14, "snowy", 7, 82, 35, false, "Lumikuuroja"),
  Juva: w("Juva", -8, -14, "snowy", 6, 82, 35, false, "Heikkoa lumisadetta"),
  Kangasniemi: w("Kangasniemi", -7, -13, "snowy", 6, 82, 35, false, "Lumikuuroja"),
  Hirvensalmi: w("Hirvensalmi", -6, -12, "cloudy", 6, 82, 35, false, "Pilvistä"),
  Mäntyharju: w("Mäntyharju", -6, -12, "snowy", 6, 82, 35, false, "Heikkoa lumisadetta"),
  Pertunmaa: w("Pertunmaa", -6, -11, "cloudy", 6, 82, 35, false, "Pilvistä"),
  Sulkava: w("Sulkava", -9, -15, "snowy", 5, 82, 30, false, "Pakkasta"),
  Rantasalmi: w("Rantasalmi", -9, -15, "snowy", 6, 82, 30, false, "Pakkasta"),
  Enonkoski: w("Enonkoski", -9, -15, "snowy", 5, 82, 30, false, "Pakkasta"),
  Puumala: w("Puumala", -8, -14, "snowy", 5, 81, 30, false, "Pakkasta"),

  // Pohjois-Savo
  Kuopio: w("Kuopio", -8, -14, "snowy", 9, 84, 55, true, "Lumisadetta iltapäivällä"),
  Siilinjärvi: w("Siilinjärvi", -9, -15, "snowy", 8, 83, 45, false, "Lumikuuroja"),
  Iisalmi: w("Iisalmi", -10, -16, "snowy", 6, 80, 25, false, "Pakkasta"),
  Varkaus: w("Varkaus", -9, -15, "snowy", 7, 82, 35, false, "Lumikuuroja"),
  Leppävirta: w("Leppävirta", -9, -15, "snowy", 7, 82, 35, false, "Heikkoa lumisadetta"),
  Suonenjoki: w("Suonenjoki", -8, -14, "snowy", 7, 82, 35, false, "Lumikuuroja"),
  Rautalampi: w("Rautalampi", -8, -14, "snowy", 7, 82, 35, false, "Heikkoa lumisadetta"),
  Tervo: w("Tervo", -8, -14, "snowy", 7, 82, 35, false, "Lumikuuroja"),
  Vesanto: w("Vesanto", -8, -14, "snowy", 7, 81, 30, false, "Pakkasta"),
  Keitele: w("Keitele", -9, -15, "snowy", 7, 81, 30, false, "Pakkasta"),
  Pielavesi: w("Pielavesi", -10, -16, "snowy", 7, 80, 25, false, "Pakkasta"),
  Kiuruvesi: w("Kiuruvesi", -10, -16, "snowy", 7, 80, 25, false, "Pakkasta"),
  Sonkajärvi: w("Sonkajärvi", -11, -17, "snowy", 6, 79, 20, false, "Kireä pakkanen"),
  Vieremä: w("Vieremä", -10, -16, "snowy", 7, 80, 25, false, "Pakkasta"),
  Lapinlahti: w("Lapinlahti", -10, -16, "snowy", 7, 81, 30, false, "Lumikuuroja"),
  Tuusniemi: w("Tuusniemi", -9, -15, "snowy", 6, 82, 30, false, "Pakkasta"),
  Kaavi: w("Kaavi", -10, -16, "snowy", 6, 81, 25, false, "Pakkasta"),
  Rautavaara: w("Rautavaara", -12, -18, "snowy", 5, 79, 15, false, "Kireä pakkanen"),

  // Pohjois-Karjala
  Joensuu: w("Joensuu", -10, -17, "snowy", 5, 81, 25, false, "Pakkasta, selkeää"),
  Kontiolahti: w("Kontiolahti", -10, -17, "snowy", 5, 81, 25, false, "Pakkasta"),
  Liperi: w("Liperi", -10, -17, "snowy", 5, 81, 25, false, "Pakkasta"),
  Outokumpu: w("Outokumpu", -10, -16, "snowy", 6, 81, 25, false, "Pakkasta"),
  Polvijärvi: w("Polvijärvi", -11, -17, "snowy", 5, 80, 20, false, "Kireä pakkanen"),
  Juuka: w("Juuka", -12, -19, "snowy", 5, 79, 20, false, "Kireä pakkanen"),
  Lieksa: w("Lieksa", -12, -19, "snowy", 5, 79, 20, false, "Kireä pakkanen"),
  Nurmes: w("Nurmes", -13, -20, "snowy", 6, 78, 15, false, "Pakkasta, selkeää"),
  Kitee: w("Kitee", -10, -16, "snowy", 5, 80, 25, false, "Pakkasta"),
  Tohmajärvi: w("Tohmajärvi", -10, -16, "snowy", 5, 80, 25, false, "Pakkasta"),
  Rääkkylä: w("Rääkkylä", -10, -16, "snowy", 5, 80, 25, false, "Pakkasta"),
  Heinävesi: w("Heinävesi", -9, -15, "snowy", 6, 81, 30, false, "Lumikuuroja"),
  Ilomantsi: w("Ilomantsi", -12, -19, "snowy", 5, 79, 15, false, "Kireä pakkanen"),
  Valtimo: w("Valtimo", -13, -20, "snowy", 6, 78, 15, false, "Pakkasta"),

  // Pohjanmaa
  Vaasa: w("Vaasa", -1, -6, "windy", 20, 86, 50, true, "Tuulista, lumikuuroja"),
  Mustasaari: w("Mustasaari", -1, -6, "windy", 18, 85, 45, true, "Tuulista"),
  Laihia: w("Laihia", -2, -7, "cloudy", 14, 83, 40, false, "Tuulista, pilvistä"),
  Isokyrö: w("Isokyrö", -3, -8, "cloudy", 12, 82, 35, false, "Pilvistä"),
  Vöyri: w("Vöyri", -2, -7, "windy", 16, 84, 45, true, "Tuulista"),
  Korsnäs: w("Korsnäs", -1, -6, "windy", 18, 85, 50, true, "Merituulta"),
  Maalahti: w("Maalahti", -1, -6, "windy", 17, 85, 45, true, "Tuulista"),
  Närpiö: w("Närpiö", 0, -5, "windy", 17, 86, 50, true, "Tuulista, kosteaa"),
  Kristiinankaupunki: w("Kristiinankaupunki", 0, -5, "windy", 16, 86, 50, true, "Merituulta"),
  Kaskinen: w("Kaskinen", 0, -5, "windy", 18, 86, 50, true, "Merituulta, tuulista"),
  Kruunupyy: w("Kruunupyy", -3, -9, "windy", 15, 84, 40, false, "Tuulista"),
  Luoto: w("Luoto", -3, -9, "windy", 16, 84, 45, true, "Merituulta"),
  Pietarsaari: w("Pietarsaari", -3, -9, "windy", 18, 85, 45, true, "Tuulista"),
  Pedersöre: w("Pedersöre", -3, -9, "cloudy", 13, 83, 40, false, "Pilvistä"),
  Uusikaarlepyy: w("Uusikaarlepyy", -2, -8, "windy", 15, 84, 40, false, "Tuulista"),

  // Etelä-Pohjanmaa
  Seinäjoki: w("Seinäjoki", -3, -8, "cloudy", 12, 80, 35, false, "Pilvistä, tyyntä"),
  Ilmajoki: w("Ilmajoki", -3, -8, "cloudy", 11, 80, 35, false, "Puolipilvistä"),
  Kurikka: w("Kurikka", -3, -8, "cloudy", 10, 80, 35, false, "Pilvistä"),
  Kauhajoki: w("Kauhajoki", -3, -8, "cloudy", 10, 81, 40, false, "Pilvistä"),
  Teuva: w("Teuva", -2, -7, "cloudy", 11, 82, 40, false, "Puolipilvistä"),
  Kauhava: w("Kauhava", -4, -10, "cloudy", 12, 81, 35, false, "Pilvistä"),
  Lapua: w("Lapua", -4, -9, "cloudy", 11, 81, 35, false, "Puolipilvistä"),
  Alavus: w("Alavus", -5, -10, "snowy", 9, 82, 40, false, "Heikkoa lumisadetta"),
  Ähtäri: w("Ähtäri", -6, -12, "snowy", 8, 82, 40, false, "Lumikuuroja"),
  Soini: w("Soini", -6, -12, "snowy", 8, 82, 40, false, "Heikkoa lumisadetta"),
  Kuortane: w("Kuortane", -5, -10, "cloudy", 10, 81, 35, false, "Pilvistä"),
  Alajärvi: w("Alajärvi", -6, -12, "snowy", 9, 81, 35, false, "Lumikuuroja"),
  Vimpeli: w("Vimpeli", -6, -12, "snowy", 9, 81, 35, false, "Heikkoa lumisadetta"),
  Lappajärvi: w("Lappajärvi", -6, -12, "snowy", 9, 81, 35, false, "Lumikuuroja"),
  Evijärvi: w("Evijärvi", -5, -11, "cloudy", 10, 81, 35, false, "Pilvistä"),

  // Keski-Pohjanmaa
  Kokkola: w("Kokkola", -4, -10, "windy", 16, 85, 45, true, "Tuulista, lumisadetta"),
  Kannus: w("Kannus", -5, -11, "cloudy", 13, 83, 40, false, "Tuulista, pilvistä"),
  Toholampi: w("Toholampi", -6, -12, "snowy", 10, 82, 35, false, "Lumikuuroja"),
  Kaustinen: w("Kaustinen", -5, -11, "cloudy", 11, 82, 35, false, "Pilvistä"),
  Veteli: w("Veteli", -5, -11, "cloudy", 11, 82, 35, false, "Puolipilvistä"),
  Halsua: w("Halsua", -6, -12, "snowy", 9, 81, 30, false, "Lumikuuroja"),
  Perho: w("Perho", -7, -13, "snowy", 9, 81, 30, false, "Pakkasta"),
  Lestijärvi: w("Lestijärvi", -7, -13, "snowy", 9, 80, 25, false, "Pakkasta"),

  // Pohjois-Pohjanmaa
  Oulu: w("Oulu", -12, -20, "snowy", 18, 78, 30, false, "Kireä pakkanen, selkeää"),
  Kempele: w("Kempele", -12, -20, "snowy", 16, 78, 30, false, "Pakkasta"),
  Liminka: w("Liminka", -12, -20, "snowy", 15, 78, 25, false, "Kireä pakkanen"),
  Muhos: w("Muhos", -13, -21, "snowy", 12, 78, 25, false, "Pakkasta"),
  Tyrnävä: w("Tyrnävä", -12, -20, "snowy", 14, 78, 25, false, "Pakkasta"),
  Lumijoki: w("Lumijoki", -11, -19, "snowy", 15, 79, 30, false, "Pakkasta"),
  Hailuoto: w("Hailuoto", -10, -18, "windy", 20, 80, 35, false, "Tuulista saarella"),
  Ii: w("Ii", -13, -21, "snowy", 14, 78, 25, false, "Pakkasta"),
  Pudasjärvi: w("Pudasjärvi", -15, -23, "snowy", 8, 77, 15, false, "Kova pakkanen"),
  Utajärvi: w("Utajärvi", -13, -21, "snowy", 10, 78, 20, false, "Pakkasta"),
  Vaala: w("Vaala", -13, -20, "snowy", 9, 78, 20, false, "Pakkasta"),
  Siikalatva: w("Siikalatva", -12, -19, "snowy", 10, 79, 25, false, "Pakkasta"),
  Haapavesi: w("Haapavesi", -10, -17, "snowy", 10, 79, 30, false, "Lumikuuroja"),
  Siikajoki: w("Siikajoki", -11, -18, "windy", 14, 79, 30, false, "Tuulista"),
  Raahe: w("Raahe", -10, -17, "windy", 15, 79, 30, false, "Tuulista, pakkasta"),
  Pyhäjoki: w("Pyhäjoki", -10, -17, "windy", 14, 79, 30, false, "Merituulta"),
  Merijärvi: w("Merijärvi", -9, -16, "cloudy", 11, 80, 30, false, "Pilvistä"),
  Oulainen: w("Oulainen", -9, -15, "snowy", 10, 80, 30, false, "Lumikuuroja"),
  Kalajoki: w("Kalajoki", -8, -15, "windy", 15, 81, 35, false, "Merituulta"),
  Alavieska: w("Alavieska", -8, -14, "cloudy", 10, 80, 30, false, "Pilvistä"),
  Ylivieska: w("Ylivieska", -8, -14, "cloudy", 10, 80, 35, false, "Pilvistä"),
  Nivala: w("Nivala", -9, -15, "snowy", 9, 80, 30, false, "Lumikuuroja"),
  Haapajärvi: w("Haapajärvi", -10, -16, "snowy", 9, 80, 25, false, "Pakkasta"),
  Reisjärvi: w("Reisjärvi", -9, -15, "snowy", 9, 80, 30, false, "Lumikuuroja"),
  Pyhäjärvi: w("Pyhäjärvi", -11, -17, "snowy", 8, 79, 25, false, "Pakkasta"),
  Kärsämäki: w("Kärsämäki", -11, -17, "snowy", 9, 79, 25, false, "Pakkasta"),
  Pyhäntä: w("Pyhäntä", -12, -18, "snowy", 8, 78, 20, false, "Kireä pakkanen"),
  Taivalkoski: w("Taivalkoski", -16, -24, "snowy", 7, 76, 10, false, "Kova pakkanen"),
  Kuusamo: w("Kuusamo", -16, -24, "snowy", 8, 76, 10, false, "Kova pakkanen, tyyntä"),

  // Kainuu
  Kajaani: w("Kajaani", -13, -20, "snowy", 8, 78, 20, false, "Kireä pakkanen"),
  Sotkamo: w("Sotkamo", -14, -21, "snowy", 7, 78, 15, false, "Pakkasta"),
  Kuhmo: w("Kuhmo", -15, -22, "snowy", 6, 77, 15, false, "Kova pakkanen"),
  Paltamo: w("Paltamo", -13, -20, "snowy", 8, 78, 20, false, "Pakkasta"),
  Ristijärvi: w("Ristijärvi", -14, -21, "snowy", 7, 78, 15, false, "Kireä pakkanen"),
  Hyrynsalmi: w("Hyrynsalmi", -15, -23, "snowy", 6, 77, 10, false, "Kova pakkanen"),
  Suomussalmi: w("Suomussalmi", -16, -24, "snowy", 6, 76, 10, false, "Kova pakkanen"),
  Puolanka: w("Puolanka", -15, -22, "snowy", 7, 77, 15, false, "Pakkasta"),

  // Lappi
  Rovaniemi: w("Rovaniemi", -18, -26, "snowy", 6, 75, 10, false, "Kova pakkanen, tyyntä"),
  Tornio: w("Tornio", -15, -23, "snowy", 10, 76, 15, false, "Kova pakkanen"),
  Kemi: w("Kemi", -14, -22, "snowy", 12, 77, 20, false, "Pakkasta, lumikuuroja"),
  Keminmaa: w("Keminmaa", -15, -23, "snowy", 10, 76, 15, false, "Pakkasta"),
  Tervola: w("Tervola", -16, -24, "snowy", 8, 76, 10, false, "Kova pakkanen"),
  Simo: w("Simo", -14, -22, "snowy", 12, 77, 20, false, "Pakkasta"),
  Ranua: w("Ranua", -18, -26, "snowy", 6, 75, 10, false, "Kova pakkanen"),
  Posio: w("Posio", -18, -26, "snowy", 6, 75, 10, false, "Kova pakkanen"),
  Kemijärvi: w("Kemijärvi", -19, -27, "snowy", 6, 75, 10, false, "Ankara pakkanen"),
  Pelkosenniemi: w("Pelkosenniemi", -20, -28, "snowy", 5, 74, 5, false, "Ankara pakkanen"),
  Salla: w("Salla", -20, -28, "snowy", 5, 74, 5, false, "Ankara pakkanen"),
  Savukoski: w("Savukoski", -22, -30, "snowy", 4, 73, 5, false, "Ankara pakkanen"),
  Sodankylä: w("Sodankylä", -20, -28, "snowy", 5, 74, 5, false, "Ankara pakkanen"),
  Kittilä: w("Kittilä", -20, -28, "snowy", 6, 74, 5, false, "Ankara pakkanen"),
  Kolari: w("Kolari", -19, -27, "snowy", 6, 75, 10, false, "Kova pakkanen"),
  Muonio: w("Muonio", -21, -29, "snowy", 5, 74, 5, false, "Ankara pakkanen"),
  Enontekiö: w("Enontekiö", -22, -30, "snowy", 6, 73, 5, false, "Ankara pakkanen, tunturituulta"),
  Pello: w("Pello", -18, -26, "snowy", 7, 75, 10, false, "Kova pakkanen"),
  Ylitornio: w("Ylitornio", -17, -25, "snowy", 8, 76, 10, false, "Kova pakkanen"),
  Inari: w("Inari", -22, -30, "snowy", 4, 73, 5, false, "Ankara pakkanen, tyyntä"),
  Utsjoki: w("Utsjoki", -24, -32, "snowy", 6, 72, 5, false, "Kova pakkanen, kaamos"),

  // Ahvenanmaa
  Maarianhamina: w("Maarianhamina", 2, -2, "rainy", 14, 88, 70, true, "Merituulta, tihkusadetta"),
  Jomala: w("Jomala", 2, -2, "rainy", 13, 87, 65, true, "Merituulta"),
  Finström: w("Finström", 2, -2, "windy", 15, 87, 65, true, "Tuulista saaristossa"),
  Saltvik: w("Saltvik", 2, -2, "windy", 14, 87, 60, true, "Merituulta"),
  Sund: w("Sund", 2, -2, "cloudy", 13, 86, 55, false, "Pilvistä"),
  Hammarland: w("Hammarland", 2, -2, "windy", 15, 87, 65, true, "Tuulista"),
  Eckerö: w("Eckerö", 2, -1, "windy", 17, 88, 65, true, "Merituulta"),
  Lemland: w("Lemland", 2, -2, "rainy", 14, 87, 65, true, "Sadetta"),
  Lumparland: w("Lumparland", 2, -2, "cloudy", 13, 86, 55, false, "Pilvistä"),
  Geta: w("Geta", 2, -2, "windy", 16, 87, 60, true, "Tuulista"),
  Kumlinge: w("Kumlinge", 2, -1, "windy", 18, 88, 60, true, "Merituulta saaristossa"),
  Brändö: w("Brändö", 2, -1, "windy", 17, 88, 60, true, "Tuulista saaristossa"),
  Föglö: w("Föglö", 2, -1, "windy", 16, 87, 60, true, "Merituulta"),
  Kökar: w("Kökar", 2, -1, "windy", 19, 88, 65, true, "Merituulta, tuulista"),
  Sottunga: w("Sottunga", 2, -1, "windy", 18, 88, 60, true, "Merituulta"),
  Vårdö: w("Vårdö", 2, -2, "windy", 15, 87, 60, true, "Tuulista"),
};

// Swedish cities
export const citiesSE: Record<string, WeatherData> = {
  Stockholm: w("Stockholm", 2, -2, "cloudy", 8, 80, 40, false, "Molnigt"),
  Göteborg: w("Göteborg", 4, 0, "rainy", 12, 85, 70, true, "Regn"),
  Malmö: w("Malmö", 5, 1, "windy", 14, 82, 55, true, "Blåsigt"),
  Uppsala: w("Uppsala", 1, -3, "cloudy", 7, 78, 35, false, "Molnigt"),
  Linköping: w("Linköping", 3, -1, "cloudy", 9, 79, 40, false, "Molnigt"),
  Västerås: w("Västerås", 2, -2, "cloudy", 8, 79, 35, false, "Halvmolnigt"),
  Örebro: w("Örebro", 2, -2, "cloudy", 9, 80, 40, false, "Molnigt"),
  Norrköping: w("Norrköping", 3, -1, "cloudy", 9, 80, 40, false, "Molnigt"),
  Helsingborg: w("Helsingborg", 5, 1, "windy", 13, 82, 50, true, "Blåsigt"),
  Jönköping: w("Jönköping", 2, -2, "cloudy", 8, 80, 40, false, "Molnigt"),
  Umeå: w("Umeå", -5, -11, "snowy", 10, 78, 30, false, "Snö"),
  Lund: w("Lund", 5, 1, "windy", 13, 82, 50, true, "Blåsigt"),
  Borås: w("Borås", 3, -1, "rainy", 10, 84, 65, true, "Regn"),
  Sundsvall: w("Sundsvall", -4, -10, "snowy", 9, 79, 30, false, "Snöfall"),
  Gävle: w("Gävle", 0, -5, "cloudy", 8, 80, 35, false, "Molnigt"),
  Luleå: w("Luleå", -10, -17, "snowy", 8, 76, 20, false, "Kallt"),
  Karlstad: w("Karlstad", 1, -3, "cloudy", 8, 80, 40, false, "Halvmolnigt"),
  Växjö: w("Växjö", 3, -1, "cloudy", 8, 81, 45, false, "Molnigt"),
  Halmstad: w("Halmstad", 5, 1, "windy", 14, 83, 55, true, "Blåsigt"),
  Kalmar: w("Kalmar", 4, 0, "windy", 11, 81, 45, true, "Havsvind"),
  Kiruna: w("Kiruna", -15, -23, "snowy", 6, 74, 10, false, "Kallt, snö"),
  Skellefteå: w("Skellefteå", -7, -13, "snowy", 9, 77, 25, false, "Snöfall"),
  Falun: w("Falun", -1, -6, "cloudy", 7, 79, 35, false, "Molnigt"),
  Trollhättan: w("Trollhättan", 3, -1, "rainy", 10, 83, 60, true, "Regn"),
  Östersund: w("Östersund", -8, -14, "snowy", 7, 77, 20, false, "Kallt, snö"),
  Visby: w("Visby", 3, -1, "windy", 13, 83, 45, true, "Havsvind"),
  Kristianstad: w("Kristianstad", 4, 0, "cloudy", 10, 81, 45, false, "Molnigt"),
  Karlskrona: w("Karlskrona", 4, 0, "windy", 12, 82, 50, true, "Havsvind"),
};

// Norwegian cities
export const citiesNO: Record<string, WeatherData> = {
  Oslo: w("Oslo", 1, -3, "cloudy", 7, 78, 40, false, "Skyet"),
  Bergen: w("Bergen", 5, 1, "rainy", 10, 90, 85, true, "Regn"),
  Trondheim: w("Trondheim", -1, -6, "snowy", 9, 80, 45, true, "Snø"),
  Stavanger: w("Stavanger", 5, 1, "rainy", 14, 88, 75, true, "Regn og vind"),
  Drammen: w("Drammen", 1, -3, "cloudy", 7, 78, 40, false, "Skyet"),
  Kristiansand: w("Kristiansand", 4, 0, "cloudy", 10, 82, 50, false, "Skyet"),
  Fredrikstad: w("Fredrikstad", 2, -2, "cloudy", 8, 79, 40, false, "Skyet"),
  Tromsø: w("Tromsø", -5, -11, "snowy", 10, 78, 30, false, "Snø, kaldt"),
  Sandnes: w("Sandnes", 5, 1, "rainy", 13, 87, 70, true, "Regn"),
  Bodø: w("Bodø", -3, -9, "windy", 15, 79, 35, false, "Vind og snø"),
  Ålesund: w("Ålesund", 3, -1, "rainy", 12, 87, 70, true, "Regn"),
  Tønsberg: w("Tønsberg", 2, -2, "cloudy", 8, 79, 40, false, "Skyet"),
  Haugesund: w("Haugesund", 5, 1, "rainy", 14, 88, 75, true, "Regn"),
  Sandefjord: w("Sandefjord", 2, -2, "cloudy", 9, 80, 40, false, "Halvskyet"),
  Molde: w("Molde", 2, -2, "rainy", 10, 85, 60, true, "Regn"),
  Harstad: w("Harstad", -4, -10, "snowy", 10, 78, 30, false, "Snø"),
  Narvik: w("Narvik", -6, -12, "snowy", 8, 77, 25, false, "Snø, kaldt"),
  Alta: w("Alta", -10, -17, "snowy", 7, 75, 15, false, "Kaldt"),
  Lillehammer: w("Lillehammer", -3, -8, "snowy", 6, 78, 30, false, "Snø"),
  Hammerfest: w("Hammerfest", -8, -15, "snowy", 12, 76, 20, false, "Kaldt, vind"),
};

// Danish cities
export const citiesDK: Record<string, WeatherData> = {
  København: w("København", 5, 1, "cloudy", 10, 80, 45, false, "Overskyet"),
  Aarhus: w("Aarhus", 4, 0, "cloudy", 11, 81, 50, true, "Overskyet"),
  Odense: w("Odense", 5, 1, "cloudy", 10, 80, 45, false, "Halvskyet"),
  Aalborg: w("Aalborg", 3, -1, "windy", 13, 82, 50, true, "Blæsende"),
  Esbjerg: w("Esbjerg", 5, 1, "windy", 16, 84, 60, true, "Blæsende, regn"),
  Randers: w("Randers", 4, 0, "cloudy", 10, 80, 45, false, "Overskyet"),
  Kolding: w("Kolding", 5, 1, "cloudy", 11, 81, 50, false, "Halvskyet"),
  Horsens: w("Horsens", 4, 0, "cloudy", 10, 80, 45, false, "Overskyet"),
  Vejle: w("Vejle", 5, 1, "cloudy", 10, 80, 45, false, "Halvskyet"),
  Roskilde: w("Roskilde", 5, 1, "cloudy", 9, 80, 40, false, "Overskyet"),
  Herning: w("Herning", 4, 0, "windy", 13, 82, 55, true, "Blæsende"),
  Silkeborg: w("Silkeborg", 4, 0, "cloudy", 9, 80, 40, false, "Halvskyet"),
  Helsingør: w("Helsingør", 5, 1, "windy", 12, 82, 50, true, "Havvind"),
  Næstved: w("Næstved", 5, 1, "cloudy", 9, 80, 40, false, "Overskyet"),
  Fredericia: w("Fredericia", 5, 1, "windy", 12, 82, 50, true, "Blæsende"),
  Viborg: w("Viborg", 3, -1, "cloudy", 10, 80, 45, false, "Halvskyet"),
  Sønderborg: w("Sønderborg", 4, 0, "windy", 13, 82, 55, true, "Havvind"),
  Svendborg: w("Svendborg", 5, 1, "cloudy", 10, 81, 45, false, "Halvskyet"),
};

/** Get cities for a specific country */
export function getCitiesByCountry(country: Country): Record<string, WeatherData> {
  switch (country) {
    case "SE": return citiesSE;
    case "NO": return citiesNO;
    case "DK": return citiesDK;
    default: return cityWeather;
  }
}

/** Get all cities across all countries */
export function getAllCities(): string[] {
  return [
    ...Object.keys(cityWeather),
    ...Object.keys(citiesSE),
    ...Object.keys(citiesNO),
    ...Object.keys(citiesDK),
  ];
}
